# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.screener_data.v1 import screener_data_pb2 as systemathics_dot_apis_dot_services_dot_screener__data_dot_v1_dot_screener__data__pb2


class ScreenerServiceStub(object):
    """Called to request screener data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Screener = channel.unary_unary(
                '/systemathics.apis.services.screener_data.v1.ScreenerService/Screener',
                request_serializer=systemathics_dot_apis_dot_services_dot_screener__data_dot_v1_dot_screener__data__pb2.ScreenerRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_screener__data_dot_v1_dot_screener__data__pb2.ScreenerResponse.FromString,
                )


class ScreenerServiceServicer(object):
    """Called to request screener data.
    """

    def Screener(self, request, context):
        """Gets screener data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScreenerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Screener': grpc.unary_unary_rpc_method_handler(
                    servicer.Screener,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_screener__data_dot_v1_dot_screener__data__pb2.ScreenerRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_screener__data_dot_v1_dot_screener__data__pb2.ScreenerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.screener_data.v1.ScreenerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScreenerService(object):
    """Called to request screener data.
    """

    @staticmethod
    def Screener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.screener_data.v1.ScreenerService/Screener',
            systemathics_dot_apis_dot_services_dot_screener__data_dot_v1_dot_screener__data__pb2.ScreenerRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_screener__data_dot_v1_dot_screener__data__pb2.ScreenerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
