# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.private.v1 import identifier_mapping_pb2 as systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_identifier__mapping__pb2


class IdentifierMappingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IdentifierMapping = channel.unary_unary(
                '/systemathics.apis.services.private.v1.IdentifierMappingService/IdentifierMapping',
                request_serializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_identifier__mapping__pb2.IdentifierMappingRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_identifier__mapping__pb2.IdentifierMappingResponse.FromString,
                )


class IdentifierMappingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IdentifierMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentifierMappingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IdentifierMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.IdentifierMapping,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_identifier__mapping__pb2.IdentifierMappingRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_identifier__mapping__pb2.IdentifierMappingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.private.v1.IdentifierMappingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdentifierMappingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IdentifierMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.private.v1.IdentifierMappingService/IdentifierMapping',
            systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_identifier__mapping__pb2.IdentifierMappingRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_identifier__mapping__pb2.IdentifierMappingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
