# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.private.v1 import memos_pb2 as systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_memos__pb2


class MemosServiceStub(object):
    """The memos service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Memos = channel.unary_unary(
                '/systemathics.apis.services.private.v1.MemosService/Memos',
                request_serializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_memos__pb2.MemosRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_memos__pb2.MemosResponse.FromString,
                )


class MemosServiceServicer(object):
    """The memos service definition
    """

    def Memos(self, request, context):
        """Get Memos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Memos': grpc.unary_unary_rpc_method_handler(
                    servicer.Memos,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_memos__pb2.MemosRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_memos__pb2.MemosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.private.v1.MemosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MemosService(object):
    """The memos service definition
    """

    @staticmethod
    def Memos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.private.v1.MemosService/Memos',
            systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_memos__pb2.MemosRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_private_dot_v1_dot_memos__pb2.MemosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
