# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.tick_analytics.v1 import tick_trade_conditions_pb2 as systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__trade__conditions__pb2


class TickTradeConditionsServiceStub(object):
    """Called to request tick by tick trade condition statistics.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TickTradeConditions = channel.unary_stream(
                '/systemathics.apis.services.tick_analytics.v1.TickTradeConditionsService/TickTradeConditions',
                request_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__trade__conditions__pb2.TickTradeConditionsRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__trade__conditions__pb2.TickTradeConditionsResponse.FromString,
                )


class TickTradeConditionsServiceServicer(object):
    """Called to request tick by tick trade condition statistics.
    """

    def TickTradeConditions(self, request, context):
        """Gets tick by tick trade conditions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickTradeConditionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TickTradeConditions': grpc.unary_stream_rpc_method_handler(
                    servicer.TickTradeConditions,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__trade__conditions__pb2.TickTradeConditionsRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__trade__conditions__pb2.TickTradeConditionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.tick_analytics.v1.TickTradeConditionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TickTradeConditionsService(object):
    """Called to request tick by tick trade condition statistics.
    """

    @staticmethod
    def TickTradeConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/systemathics.apis.services.tick_analytics.v1.TickTradeConditionsService/TickTradeConditions',
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__trade__conditions__pb2.TickTradeConditionsRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__trade__conditions__pb2.TickTradeConditionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
