# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.tick_analytics.v1 import tick_spread_pb2 as systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__spread__pb2


class TickSpreadServiceStub(object):
    """Called to request TickSpreadService. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TickSpread = channel.unary_stream(
                '/systemathics.apis.services.tick_analytics.v1.TickSpreadService/TickSpread',
                request_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__spread__pb2.TickSpreadRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__spread__pb2.TickSpreadResponse.FromString,
                )


class TickSpreadServiceServicer(object):
    """Called to request TickSpreadService. 
    """

    def TickSpread(self, request, context):
        """Gets the Spread analytics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickSpreadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TickSpread': grpc.unary_stream_rpc_method_handler(
                    servicer.TickSpread,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__spread__pb2.TickSpreadRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__spread__pb2.TickSpreadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.tick_analytics.v1.TickSpreadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TickSpreadService(object):
    """Called to request TickSpreadService. 
    """

    @staticmethod
    def TickSpread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/systemathics.apis.services.tick_analytics.v1.TickSpreadService/TickSpread',
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__spread__pb2.TickSpreadRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v1_dot_tick__spread__pb2.TickSpreadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
