# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily.v1 import daily_bars_pb2 as systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__bars__pb2


class DailyBarsServiceStub(object):
    """Called to request daily bars data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyBars = channel.unary_unary(
                '/systemathics.apis.services.daily.v1.DailyBarsService/DailyBars',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__bars__pb2.DailyBarsRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__bars__pb2.DailyBarsResponse.FromString,
                )


class DailyBarsServiceServicer(object):
    """Called to request daily bars data. 
    """

    def DailyBars(self, request, context):
        """Gets daily historical data: date, open, high, low, close and volume
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyBarsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyBars': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyBars,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__bars__pb2.DailyBarsRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__bars__pb2.DailyBarsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily.v1.DailyBarsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyBarsService(object):
    """Called to request daily bars data. 
    """

    @staticmethod
    def DailyBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily.v1.DailyBarsService/DailyBars',
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__bars__pb2.DailyBarsRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__bars__pb2.DailyBarsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
