# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily.v1 import daily_market_data_pb2 as systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__pb2


class DailyMarketDataServiceStub(object):
    """Called to request daily MarketData data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyMarketData = channel.unary_unary(
                '/systemathics.apis.services.daily.v1.DailyMarketDataService/DailyMarketData',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__pb2.DailyMarketDataRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__pb2.DailyMarketDataResponse.FromString,
                )


class DailyMarketDataServiceServicer(object):
    """Called to request daily MarketData data. 
    """

    def DailyMarketData(self, request, context):
        """Gets daily historical marketdata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyMarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyMarketData,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__pb2.DailyMarketDataRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__pb2.DailyMarketDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily.v1.DailyMarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyMarketDataService(object):
    """Called to request daily MarketData data. 
    """

    @staticmethod
    def DailyMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily.v1.DailyMarketDataService/DailyMarketData',
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__pb2.DailyMarketDataRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__pb2.DailyMarketDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
