# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily.v1 import daily_vwap_pb2 as systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__vwap__pb2


class DailyVwapsServiceStub(object):
    """Called to request daily VWAP data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyVwaps = channel.unary_unary(
                '/systemathics.apis.services.daily.v1.DailyVwapsService/DailyVwaps',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__vwap__pb2.DailyVwapsRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__vwap__pb2.DailyVwapsResponse.FromString,
                )


class DailyVwapsServiceServicer(object):
    """Called to request daily VWAP data. 
    """

    def DailyVwaps(self, request, context):
        """Gets daily historical VWAPs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyVwapsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyVwaps': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyVwaps,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__vwap__pb2.DailyVwapsRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__vwap__pb2.DailyVwapsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily.v1.DailyVwapsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyVwapsService(object):
    """Called to request daily VWAP data. 
    """

    @staticmethod
    def DailyVwaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily.v1.DailyVwapsService/DailyVwaps',
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__vwap__pb2.DailyVwapsRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__vwap__pb2.DailyVwapsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
