# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/services/daily/v1/daily_prices.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.type import date_pb2 as google_dot_type_dot_date__pb2
from systemathics.apis.type.shared.v1 import identifier_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_identifier__pb2
from systemathics.apis.type.shared.v1 import date_interval_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_date__interval__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6systemathics/apis/services/daily/v1/daily_prices.proto\x12#systemathics.apis.services.daily.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16google/type/date.proto\x1a\x31systemathics/apis/type/shared/v1/identifier.proto\x1a\x34systemathics/apis/type/shared/v1/date_interval.proto\"\xd7\x01\n\x12\x44\x61ilyPricesRequest\x12L\n\nidentifier\x18\x01 \x01(\x0b\x32,.systemathics.apis.type.shared.v1.IdentifierR\nidentifier\x12S\n\rdate_interval\x18\x02 \x01(\x0b\x32..systemathics.apis.type.shared.v1.DateIntervalR\x0c\x64\x61teInterval\x12\x1e\n\nadjustment\x18\x03 \x01(\x08R\nadjustment\"Z\n\x13\x44\x61ilyPricesResponse\x12\x43\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32/.systemathics.apis.services.daily.v1.DailyPriceR\x04\x64\x61ta\"w\n\nDailyPrice\x12%\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x11.google.type.DateR\x04\x64\x61te\x12\x14\n\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x14\n\x05score\x18\x04 \x01(\x01R\x05score2\xb1\x01\n\x12\x44\x61ilyPricesService\x12\x9a\x01\n\x0b\x44\x61ilyPrices\x12\x37.systemathics.apis.services.daily.v1.DailyPricesRequest\x1a\x38.systemathics.apis.services.daily.v1.DailyPricesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/daily/pricesB\xec\x01\n\'com.systemathics.apis.services.daily.v1B\x10\x44\x61ilyPricesProtoP\x01\xa2\x02\x04SASD\xaa\x02#Systemathics.Apis.Services.Daily.V1\xca\x02#Systemathics\\Apis\\Services\\Daily\\V1\xe2\x02/Systemathics\\Apis\\Services\\Daily\\V1\\GPBMetadata\xea\x02\'Systemathics::Apis::Services::Daily::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systemathics.apis.services.daily.v1.daily_prices_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.systemathics.apis.services.daily.v1B\020DailyPricesProtoP\001\242\002\004SASD\252\002#Systemathics.Apis.Services.Daily.V1\312\002#Systemathics\\Apis\\Services\\Daily\\V1\342\002/Systemathics\\Apis\\Services\\Daily\\V1\\GPBMetadata\352\002\'Systemathics::Apis::Services::Daily::V1'
  _globals['_DAILYPRICESSERVICE'].methods_by_name['DailyPrices']._options = None
  _globals['_DAILYPRICESSERVICE'].methods_by_name['DailyPrices']._serialized_options = b'\202\323\344\223\002\022\022\020/v1/daily/prices'
  _globals['_DAILYPRICESREQUEST']._serialized_start=255
  _globals['_DAILYPRICESREQUEST']._serialized_end=470
  _globals['_DAILYPRICESRESPONSE']._serialized_start=472
  _globals['_DAILYPRICESRESPONSE']._serialized_end=562
  _globals['_DAILYPRICE']._serialized_start=564
  _globals['_DAILYPRICE']._serialized_end=683
  _globals['_DAILYPRICESSERVICE']._serialized_start=686
  _globals['_DAILYPRICESSERVICE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
