# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily.v1 import daily_market_data_by_underlying_pb2 as systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__by__underlying__pb2


class DailyMarketDataByUnderlyingServiceStub(object):
    """Called to request daily MarketData data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyMarketDataByUnderlying = channel.unary_unary(
                '/systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingService/DailyMarketDataByUnderlying',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__by__underlying__pb2.DailyMarketDataByUnderlyingRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__by__underlying__pb2.DailyMarketDataByUnderlyingResponse.FromString,
                )


class DailyMarketDataByUnderlyingServiceServicer(object):
    """Called to request daily MarketData data. 
    """

    def DailyMarketDataByUnderlying(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyMarketDataByUnderlyingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyMarketDataByUnderlying': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyMarketDataByUnderlying,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__by__underlying__pb2.DailyMarketDataByUnderlyingRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__by__underlying__pb2.DailyMarketDataByUnderlyingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyMarketDataByUnderlyingService(object):
    """Called to request daily MarketData data. 
    """

    @staticmethod
    def DailyMarketDataByUnderlying(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingService/DailyMarketDataByUnderlying',
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__by__underlying__pb2.DailyMarketDataByUnderlyingRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__market__data__by__underlying__pb2.DailyMarketDataByUnderlyingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
