# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily.v1 import daily_prices_pb2 as systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__prices__pb2


class DailyPricesServiceStub(object):
    """Called to request daily prices data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyPrices = channel.unary_unary(
                '/systemathics.apis.services.daily.v1.DailyPricesService/DailyPrices',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__prices__pb2.DailyPricesRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__prices__pb2.DailyPricesResponse.FromString,
                )


class DailyPricesServiceServicer(object):
    """Called to request daily prices data. 
    """

    def DailyPrices(self, request, context):
        """Gets daily historical prices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyPricesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyPrices,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__prices__pb2.DailyPricesRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__prices__pb2.DailyPricesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily.v1.DailyPricesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyPricesService(object):
    """Called to request daily prices data. 
    """

    @staticmethod
    def DailyPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily.v1.DailyPricesService/DailyPrices',
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__prices__pb2.DailyPricesRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily_dot_v1_dot_daily__prices__pb2.DailyPricesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
