# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily_analytics.v1 import daily_macd_pb2 as systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__macd__pb2


class DailyMacdServiceStub(object):
    """Called to request daily moving average convergence divergence data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyMacd = channel.unary_unary(
                '/systemathics.apis.services.daily_analytics.v1.DailyMacdService/DailyMacd',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__macd__pb2.DailyMacdRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__macd__pb2.DailyMacdResponse.FromString,
                )


class DailyMacdServiceServicer(object):
    """Called to request daily moving average convergence divergence data. 
    """

    def DailyMacd(self, request, context):
        """Gets daily moving average convergence divergence data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyMacdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyMacd': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyMacd,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__macd__pb2.DailyMacdRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__macd__pb2.DailyMacdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily_analytics.v1.DailyMacdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyMacdService(object):
    """Called to request daily moving average convergence divergence data. 
    """

    @staticmethod
    def DailyMacd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily_analytics.v1.DailyMacdService/DailyMacd',
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__macd__pb2.DailyMacdRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__macd__pb2.DailyMacdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
