# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily_analytics.v1 import daily_sma_pb2 as systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__sma__pb2


class DailySmaServiceStub(object):
    """Called to request daily simple moving average data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailySma = channel.unary_unary(
                '/systemathics.apis.services.daily_analytics.v1.DailySmaService/DailySma',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__sma__pb2.DailySmaRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__sma__pb2.DailySmaResponse.FromString,
                )


class DailySmaServiceServicer(object):
    """Called to request daily simple moving average data. 
    """

    def DailySma(self, request, context):
        """Gets daily simple moving average data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailySmaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailySma': grpc.unary_unary_rpc_method_handler(
                    servicer.DailySma,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__sma__pb2.DailySmaRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__sma__pb2.DailySmaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily_analytics.v1.DailySmaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailySmaService(object):
    """Called to request daily simple moving average data. 
    """

    @staticmethod
    def DailySma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily_analytics.v1.DailySmaService/DailySma',
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__sma__pb2.DailySmaRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__sma__pb2.DailySmaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
