# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily_analytics.v1 import daily_volatility_pb2 as systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__volatility__pb2


class DailyVolatilityServiceStub(object):
    """Called to request daily volatility data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyVolatility = channel.unary_unary(
                '/systemathics.apis.services.daily_analytics.v1.DailyVolatilityService/DailyVolatility',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__volatility__pb2.DailyVolatilityRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__volatility__pb2.DailyVolatilityResponse.FromString,
                )


class DailyVolatilityServiceServicer(object):
    """Called to request daily volatility data. 
    """

    def DailyVolatility(self, request, context):
        """Gets daily historical volatility
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyVolatilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyVolatility': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyVolatility,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__volatility__pb2.DailyVolatilityRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__volatility__pb2.DailyVolatilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily_analytics.v1.DailyVolatilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyVolatilityService(object):
    """Called to request daily volatility data. 
    """

    @staticmethod
    def DailyVolatility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily_analytics.v1.DailyVolatilityService/DailyVolatility',
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__volatility__pb2.DailyVolatilityRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__volatility__pb2.DailyVolatilityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
