# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.daily_analytics.v1 import daily_ema_pb2 as systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__ema__pb2


class DailyEmaServiceStub(object):
    """Called to request daily exponential moving average data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DailyEma = channel.unary_unary(
                '/systemathics.apis.services.daily_analytics.v1.DailyEmaService/DailyEma',
                request_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__ema__pb2.DailyEmaRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__ema__pb2.DailyEmaResponse.FromString,
                )


class DailyEmaServiceServicer(object):
    """Called to request daily exponential moving average data. 
    """

    def DailyEma(self, request, context):
        """Gets daily exponential moving average data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DailyEmaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DailyEma': grpc.unary_unary_rpc_method_handler(
                    servicer.DailyEma,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__ema__pb2.DailyEmaRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__ema__pb2.DailyEmaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.daily_analytics.v1.DailyEmaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DailyEmaService(object):
    """Called to request daily exponential moving average data. 
    """

    @staticmethod
    def DailyEma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.daily_analytics.v1.DailyEmaService/DailyEma',
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__ema__pb2.DailyEmaRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_daily__analytics_dot_v1_dot_daily__ema__pb2.DailyEmaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
