# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/services/intraday_analytics/v1/intraday_volatility.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from systemathics.apis.type.shared.v1 import identifier_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_identifier__pb2
from systemathics.apis.type.shared.v1 import date_interval_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_date__interval__pb2
from systemathics.apis.type.shared.v1 import sampling_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_sampling__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJsystemathics/apis/services/intraday_analytics/v1/intraday_volatility.proto\x12\x30systemathics.apis.services.intraday_analytics.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x31systemathics/apis/type/shared/v1/identifier.proto\x1a\x34systemathics/apis/type/shared/v1/date_interval.proto\x1a/systemathics/apis/type/shared/v1/sampling.proto\"\xa6\x02\n\x19IntradayVolatilityRequest\x12L\n\nidentifier\x18\x01 \x01(\x0b\x32,.systemathics.apis.type.shared.v1.IdentifierR\nidentifier\x12\x46\n\x08sampling\x18\x02 \x01(\x0e\x32*.systemathics.apis.type.shared.v1.SamplingR\x08sampling\x12S\n\rdate_interval\x18\x03 \x01(\x0b\x32..systemathics.apis.type.shared.v1.DateIntervalR\x0c\x64\x61teInterval\x12\x1e\n\nadjustment\x18\x04 \x01(\x08R\nadjustment\"2\n\x1aIntradayVolatilityResponse\x12\x14\n\x05value\x18\x01 \x01(\x01R\x05value2\xee\x01\n\x19IntradayVolatilityService\x12\xd0\x01\n\x12IntradayVolatility\x12K.systemathics.apis.services.intraday_analytics.v1.IntradayVolatilityRequest\x1aL.systemathics.apis.services.intraday_analytics.v1.IntradayVolatilityResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/intraday/volatilityB\xb0\x02\n4com.systemathics.apis.services.intraday_analytics.v1B\x17IntradayVolatilityProtoP\x01\xa2\x02\x04SASI\xaa\x02/Systemathics.Apis.Services.IntradayAnalytics.V1\xca\x02/Systemathics\\Apis\\Services\\IntradayAnalytics\\V1\xe2\x02;Systemathics\\Apis\\Services\\IntradayAnalytics\\V1\\GPBMetadata\xea\x02\x33Systemathics::Apis::Services::IntradayAnalytics::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systemathics.apis.services.intraday_analytics.v1.intraday_volatility_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n4com.systemathics.apis.services.intraday_analytics.v1B\027IntradayVolatilityProtoP\001\242\002\004SASI\252\002/Systemathics.Apis.Services.IntradayAnalytics.V1\312\002/Systemathics\\Apis\\Services\\IntradayAnalytics\\V1\342\002;Systemathics\\Apis\\Services\\IntradayAnalytics\\V1\\GPBMetadata\352\0023Systemathics::Apis::Services::IntradayAnalytics::V1'
  _globals['_INTRADAYVOLATILITYSERVICE'].methods_by_name['IntradayVolatility']._options = None
  _globals['_INTRADAYVOLATILITYSERVICE'].methods_by_name['IntradayVolatility']._serialized_options = b'\202\323\344\223\002\031\022\027/v1/intraday/volatility'
  _globals['_INTRADAYVOLATILITYREQUEST']._serialized_start=313
  _globals['_INTRADAYVOLATILITYREQUEST']._serialized_end=607
  _globals['_INTRADAYVOLATILITYRESPONSE']._serialized_start=609
  _globals['_INTRADAYVOLATILITYRESPONSE']._serialized_end=659
  _globals['_INTRADAYVOLATILITYSERVICE']._serialized_start=662
  _globals['_INTRADAYVOLATILITYSERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
