# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.intraday_analytics.v1 import intraday_macd_pb2 as systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__macd__pb2


class IntradayMacdServiceStub(object):
    """Called to request intraday moving average convergence divergence data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntradayMacd = channel.unary_unary(
                '/systemathics.apis.services.intraday_analytics.v1.IntradayMacdService/IntradayMacd',
                request_serializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__macd__pb2.IntradayMacdRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__macd__pb2.IntradayMacdResponse.FromString,
                )


class IntradayMacdServiceServicer(object):
    """Called to request intraday moving average convergence divergence data. 
    """

    def IntradayMacd(self, request, context):
        """Gets intraday moving average convergence divergence data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntradayMacdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntradayMacd': grpc.unary_unary_rpc_method_handler(
                    servicer.IntradayMacd,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__macd__pb2.IntradayMacdRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__macd__pb2.IntradayMacdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.intraday_analytics.v1.IntradayMacdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntradayMacdService(object):
    """Called to request intraday moving average convergence divergence data. 
    """

    @staticmethod
    def IntradayMacd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.intraday_analytics.v1.IntradayMacdService/IntradayMacd',
            systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__macd__pb2.IntradayMacdRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__macd__pb2.IntradayMacdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
