# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.intraday_analytics.v1 import intraday_bollinger_pb2 as systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__bollinger__pb2


class IntradayBollingerServiceStub(object):
    """Called to request intraday Bollinger bands data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntradayBollinger = channel.unary_unary(
                '/systemathics.apis.services.intraday_analytics.v1.IntradayBollingerService/IntradayBollinger',
                request_serializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__bollinger__pb2.IntradayBollingerRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__bollinger__pb2.IntradayBollingerResponse.FromString,
                )


class IntradayBollingerServiceServicer(object):
    """Called to request intraday Bollinger bands data. 
    """

    def IntradayBollinger(self, request, context):
        """Gets intraday Bollinger bands data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntradayBollingerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntradayBollinger': grpc.unary_unary_rpc_method_handler(
                    servicer.IntradayBollinger,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__bollinger__pb2.IntradayBollingerRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__bollinger__pb2.IntradayBollingerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.intraday_analytics.v1.IntradayBollingerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntradayBollingerService(object):
    """Called to request intraday Bollinger bands data. 
    """

    @staticmethod
    def IntradayBollinger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.intraday_analytics.v1.IntradayBollingerService/IntradayBollinger',
            systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__bollinger__pb2.IntradayBollingerRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__bollinger__pb2.IntradayBollingerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
