# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.intraday_analytics.v1 import intraday_sma_pb2 as systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__sma__pb2


class IntradaySmaServiceStub(object):
    """Called to request intraday simple moving average data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntradaySma = channel.unary_unary(
                '/systemathics.apis.services.intraday_analytics.v1.IntradaySmaService/IntradaySma',
                request_serializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__sma__pb2.IntradaySmaRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__sma__pb2.IntradaySmaResponse.FromString,
                )


class IntradaySmaServiceServicer(object):
    """Called to request intraday simple moving average data. 
    """

    def IntradaySma(self, request, context):
        """Gets intraday simple moving average data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntradaySmaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntradaySma': grpc.unary_unary_rpc_method_handler(
                    servicer.IntradaySma,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__sma__pb2.IntradaySmaRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__sma__pb2.IntradaySmaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.intraday_analytics.v1.IntradaySmaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntradaySmaService(object):
    """Called to request intraday simple moving average data. 
    """

    @staticmethod
    def IntradaySma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.intraday_analytics.v1.IntradaySmaService/IntradaySma',
            systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__sma__pb2.IntradaySmaRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_intraday__analytics_dot_v1_dot_intraday__sma__pb2.IntradaySmaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
