# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.tick.v1 import tick_updates_pb2 as systemathics_dot_apis_dot_services_dot_tick_dot_v1_dot_tick__updates__pb2


class TickUpdatesServiceStub(object):
    """Called to request tick by tick normalized historical data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TickUpdates = channel.unary_stream(
                '/systemathics.apis.services.tick.v1.TickUpdatesService/TickUpdates',
                request_serializer=systemathics_dot_apis_dot_services_dot_tick_dot_v1_dot_tick__updates__pb2.TickUpdatesRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_tick_dot_v1_dot_tick__updates__pb2.TickUpdatesResponse.FromString,
                )


class TickUpdatesServiceServicer(object):
    """Called to request tick by tick normalized historical data.
    """

    def TickUpdates(self, request, context):
        """Get tick by tick normalized historical Updates 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickUpdatesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TickUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.TickUpdates,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_tick_dot_v1_dot_tick__updates__pb2.TickUpdatesRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_tick_dot_v1_dot_tick__updates__pb2.TickUpdatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.tick.v1.TickUpdatesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TickUpdatesService(object):
    """Called to request tick by tick normalized historical data.
    """

    @staticmethod
    def TickUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/systemathics.apis.services.tick.v1.TickUpdatesService/TickUpdates',
            systemathics_dot_apis_dot_services_dot_tick_dot_v1_dot_tick__updates__pb2.TickUpdatesRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_tick_dot_v1_dot_tick__updates__pb2.TickUpdatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
