# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/services/intraday/v1/intraday_open_interest.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from systemathics.apis.type.shared.v1 import identifier_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_identifier__pb2
from systemathics.apis.type.shared.v1 import date_interval_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_date__interval__pb2
from systemathics.apis.type.shared.v1 import sampling_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_sampling__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCsystemathics/apis/services/intraday/v1/intraday_open_interest.proto\x12&systemathics.apis.services.intraday.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x31systemathics/apis/type/shared/v1/identifier.proto\x1a\x34systemathics/apis/type/shared/v1/date_interval.proto\x1a/systemathics/apis/type/shared/v1/sampling.proto\"\x89\x02\n\x1cIntradayOpenInterestsRequest\x12L\n\nidentifier\x18\x01 \x01(\x0b\x32,.systemathics.apis.type.shared.v1.IdentifierR\nidentifier\x12\x46\n\x08sampling\x18\x02 \x01(\x0e\x32*.systemathics.apis.type.shared.v1.SamplingR\x08sampling\x12S\n\rdate_interval\x18\x03 \x01(\x0b\x32..systemathics.apis.type.shared.v1.DateIntervalR\x0c\x64\x61teInterval\"q\n\x1dIntradayOpenInterestsResponse\x12P\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32<.systemathics.apis.services.intraday.v1.IntradayOpenInterestR\x04\x64\x61ta\"}\n\x14IntradayOpenInterest\x12\x39\n\ntime_stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimeStamp\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value\x12\x14\n\x05score\x18\x03 \x01(\x01R\x05score2\xe9\x01\n\x1cIntradayOpenInterestsService\x12\xc8\x01\n\x15IntradayOpenInterests\x12\x44.systemathics.apis.services.intraday.v1.IntradayOpenInterestsRequest\x1a\x45.systemathics.apis.services.intraday.v1.IntradayOpenInterestsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/intraday/openinterestsB\x84\x02\n*com.systemathics.apis.services.intraday.v1B\x19IntradayOpenInterestProtoP\x01\xa2\x02\x04SASI\xaa\x02&Systemathics.Apis.Services.Intraday.V1\xca\x02&Systemathics\\Apis\\Services\\Intraday\\V1\xe2\x02\x32Systemathics\\Apis\\Services\\Intraday\\V1\\GPBMetadata\xea\x02*Systemathics::Apis::Services::Intraday::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systemathics.apis.services.intraday.v1.intraday_open_interest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*com.systemathics.apis.services.intraday.v1B\031IntradayOpenInterestProtoP\001\242\002\004SASI\252\002&Systemathics.Apis.Services.Intraday.V1\312\002&Systemathics\\Apis\\Services\\Intraday\\V1\342\0022Systemathics\\Apis\\Services\\Intraday\\V1\\GPBMetadata\352\002*Systemathics::Apis::Services::Intraday::V1'
  _globals['_INTRADAYOPENINTERESTSSERVICE'].methods_by_name['IntradayOpenInterests']._options = None
  _globals['_INTRADAYOPENINTERESTSSERVICE'].methods_by_name['IntradayOpenInterests']._serialized_options = b'\202\323\344\223\002\034\022\032/v1/intraday/openinterests'
  _globals['_INTRADAYOPENINTERESTSREQUEST']._serialized_start=329
  _globals['_INTRADAYOPENINTERESTSREQUEST']._serialized_end=594
  _globals['_INTRADAYOPENINTERESTSRESPONSE']._serialized_start=596
  _globals['_INTRADAYOPENINTERESTSRESPONSE']._serialized_end=709
  _globals['_INTRADAYOPENINTEREST']._serialized_start=711
  _globals['_INTRADAYOPENINTEREST']._serialized_end=836
  _globals['_INTRADAYOPENINTERESTSSERVICE']._serialized_start=839
  _globals['_INTRADAYOPENINTERESTSSERVICE']._serialized_end=1072
# @@protoc_insertion_point(module_scope)
