# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.intraday.v1 import intraday_best_limit_pb2 as systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__best__limit__pb2


class IntradayBestLimitsServiceStub(object):
    """This service serves as a gateway to an intraday Best Limit market data service, allowing users to access historical data on the best limit order levels for various financial instruments. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntradayBestLimits = channel.unary_unary(
                '/systemathics.apis.services.intraday.v1.IntradayBestLimitsService/IntradayBestLimits',
                request_serializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__best__limit__pb2.IntradayBestLimitsRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__best__limit__pb2.IntradayBestLimitsResponse.FromString,
                )


class IntradayBestLimitsServiceServicer(object):
    """This service serves as a gateway to an intraday Best Limit market data service, allowing users to access historical data on the best limit order levels for various financial instruments. 
    """

    def IntradayBestLimits(self, request, context):
        """Gets intraday historical data: date, bid and ask
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntradayBestLimitsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntradayBestLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.IntradayBestLimits,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__best__limit__pb2.IntradayBestLimitsRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__best__limit__pb2.IntradayBestLimitsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.intraday.v1.IntradayBestLimitsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntradayBestLimitsService(object):
    """This service serves as a gateway to an intraday Best Limit market data service, allowing users to access historical data on the best limit order levels for various financial instruments. 
    """

    @staticmethod
    def IntradayBestLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.intraday.v1.IntradayBestLimitsService/IntradayBestLimits',
            systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__best__limit__pb2.IntradayBestLimitsRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__best__limit__pb2.IntradayBestLimitsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
