# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.intraday.v1 import intraday_implied_volatility_pb2 as systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__implied__volatility__pb2


class IntradayImpliedVolatilitiesServiceStub(object):
    """Called to request intraday ImpliedVolatility data. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntradayImpliedVolatilities = channel.unary_unary(
                '/systemathics.apis.services.intraday.v1.IntradayImpliedVolatilitiesService/IntradayImpliedVolatilities',
                request_serializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__implied__volatility__pb2.IntradayImpliedVolatilitiesRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__implied__volatility__pb2.IntradayImpliedVolatilitiesResponse.FromString,
                )


class IntradayImpliedVolatilitiesServiceServicer(object):
    """Called to request intraday ImpliedVolatility data. 
    """

    def IntradayImpliedVolatilities(self, request, context):
        """Gets intraday historical ImpliedVolatilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntradayImpliedVolatilitiesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntradayImpliedVolatilities': grpc.unary_unary_rpc_method_handler(
                    servicer.IntradayImpliedVolatilities,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__implied__volatility__pb2.IntradayImpliedVolatilitiesRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__implied__volatility__pb2.IntradayImpliedVolatilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.intraday.v1.IntradayImpliedVolatilitiesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntradayImpliedVolatilitiesService(object):
    """Called to request intraday ImpliedVolatility data. 
    """

    @staticmethod
    def IntradayImpliedVolatilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/systemathics.apis.services.intraday.v1.IntradayImpliedVolatilitiesService/IntradayImpliedVolatilities',
            systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__implied__volatility__pb2.IntradayImpliedVolatilitiesRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_intraday_dot_v1_dot_intraday__implied__volatility__pb2.IntradayImpliedVolatilitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
