# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.tick_analytics.v2 import tick_cma_hp_pb2 as systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__cma__hp__pb2


class HpTickCmaServiceStub(object):
    """Called to request tick by tick cumulative moving average data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HpTickCma = channel.unary_stream(
                '/systemathics.apis.services.tick_analytics.v2.HpTickCmaService/HpTickCma',
                request_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__cma__hp__pb2.HpTickCmaRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__cma__hp__pb2.HpTickCmaResponse.FromString,
                )


class HpTickCmaServiceServicer(object):
    """Called to request tick by tick cumulative moving average data.
    """

    def HpTickCma(self, request, context):
        """Gets tick by tick cumulative moving average data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HpTickCmaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HpTickCma': grpc.unary_stream_rpc_method_handler(
                    servicer.HpTickCma,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__cma__hp__pb2.HpTickCmaRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__cma__hp__pb2.HpTickCmaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.tick_analytics.v2.HpTickCmaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HpTickCmaService(object):
    """Called to request tick by tick cumulative moving average data.
    """

    @staticmethod
    def HpTickCma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/systemathics.apis.services.tick_analytics.v2.HpTickCmaService/HpTickCma',
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__cma__hp__pb2.HpTickCmaRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__cma__hp__pb2.HpTickCmaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
