# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from systemathics.apis.services.tick_analytics.v2 import tick_sma_hp_pb2 as systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__sma__hp__pb2


class HpTickSmaServiceStub(object):
    """Called to request tick by tick simple moving average data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HpTickSma = channel.unary_stream(
                '/systemathics.apis.services.tick_analytics.v2.HpTickSmaService/HpTickSma',
                request_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__sma__hp__pb2.HpTickSmaRequest.SerializeToString,
                response_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__sma__hp__pb2.HpTickSmaResponse.FromString,
                )


class HpTickSmaServiceServicer(object):
    """Called to request tick by tick simple moving average data.
    """

    def HpTickSma(self, request, context):
        """Gets tick by tick simple moving average data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HpTickSmaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HpTickSma': grpc.unary_stream_rpc_method_handler(
                    servicer.HpTickSma,
                    request_deserializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__sma__hp__pb2.HpTickSmaRequest.FromString,
                    response_serializer=systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__sma__hp__pb2.HpTickSmaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systemathics.apis.services.tick_analytics.v2.HpTickSmaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HpTickSmaService(object):
    """Called to request tick by tick simple moving average data.
    """

    @staticmethod
    def HpTickSma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/systemathics.apis.services.tick_analytics.v2.HpTickSmaService/HpTickSma',
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__sma__hp__pb2.HpTickSmaRequest.SerializeToString,
            systemathics_dot_apis_dot_services_dot_tick__analytics_dot_v2_dot_tick__sma__hp__pb2.HpTickSmaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
