# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systemathics/apis/type/shared/v2/market_fields_updates.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systemathics/apis/type/shared/v2/market_fields_updates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from systemathics.apis.type.shared.v2 import action_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v2_dot_action__pb2
from systemathics.apis.type.shared.v2 import field_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v2_dot_field__pb2
from systemathics.apis.type.shared.v2 import decimals_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v2_dot_decimals__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<systemathics/apis/type/shared/v2/market_fields_updates.proto\x12 systemathics.apis.type.shared.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a-systemathics/apis/type/shared/v2/action.proto\x1a,systemathics/apis/type/shared/v2/field.proto\x1a/systemathics/apis/type/shared/v2/decimals.proto\"\xcf\x01\n\x13MarketFieldsUpdates\x12\x18\n\x07mapping\x18\x01 \x01(\rR\x07mapping\x12\x39\n\ntime_stamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimeStamp\x12\x14\n\x05reset\x18\x03 \x01(\x08R\x05reset\x12M\n\x07updates\x18\x04 \x03(\x0b\x32\x33.systemathics.apis.type.shared.v2.MarketFieldUpdateR\x07updates\"\xe0\x02\n\x11MarketFieldUpdate\x12@\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32(.systemathics.apis.type.shared.v2.ActionR\x06\x61\x63tion\x12=\n\x05\x66ield\x18\x02 \x01(\x0e\x32\'.systemathics.apis.type.shared.v2.FieldR\x05\x66ield\x12\x1f\n\nlong_value\x18\x03 \x01(\x03H\x00R\tlongValue\x12#\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00R\x0b\x64oubleValue\x12V\n\rdecimal_value\x18\x05 \x01(\x0b\x32/.systemathics.apis.type.shared.v2.SignedDecimalH\x00R\x0c\x64\x65\x63imalValue\x12#\n\x0cstring_value\x18\x06 \x01(\tH\x00R\x0bstringValueB\x07\n\x05valueB\xe5\x01\n$com.systemathics.apis.type.shared.v2B\x18MarketFieldsUpdatesProtoP\x01\xa2\x02\x04SATS\xaa\x02 Systemathics.Apis.Type.Shared.V2\xca\x02 Systemathics\\Apis\\Type\\Shared\\V2\xe2\x02,Systemathics\\Apis\\Type\\Shared\\V2\\GPBMetadata\xea\x02$Systemathics::Apis::Type::Shared::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systemathics.apis.type.shared.v2.market_fields_updates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.systemathics.apis.type.shared.v2B\030MarketFieldsUpdatesProtoP\001\242\002\004SATS\252\002 Systemathics.Apis.Type.Shared.V2\312\002 Systemathics\\Apis\\Type\\Shared\\V2\342\002,Systemathics\\Apis\\Type\\Shared\\V2\\GPBMetadata\352\002$Systemathics::Apis::Type::Shared::V2'
  _globals['_MARKETFIELDSUPDATES']._serialized_start=274
  _globals['_MARKETFIELDSUPDATES']._serialized_end=481
  _globals['_MARKETFIELDUPDATE']._serialized_start=484
  _globals['_MARKETFIELDUPDATE']._serialized_end=836
# @@protoc_insertion_point(module_scope)
