# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/services/v1/memos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from systemathics.apis.type.v1 import memo_pb2 as systemathics_dot_apis_dot_type_dot_v1_dot_memo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='systemathics/apis/services/v1/memos.proto',
  package='systemathics.apis.services.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)systemathics/apis/services/v1/memos.proto\x12\x1dsystemathics.apis.services.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a$systemathics/apis/type/v1/memo.proto\"\xc2\x01\n\x0cMemosRequest\x12\x15\n\rsearch_string\x18\x01 \x01(\t\x12\x43\n\x0bsearch_type\x18\x02 \x01(\x0e\x32..systemathics.apis.services.v1.MemosSearchType\x12*\n\x05start\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12*\n\x05\x63ount\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\"Q\n\rMemosResponse\x12.\n\x05memos\x18\x01 \x03(\x0b\x32\x1f.systemathics.apis.type.v1.Memo\x12\x10\n\x08has_more\x18\x02 \x01(\x08*\x80\x01\n\x0fMemosSearchType\x12!\n\x1dMEMOS_SEARCH_TYPE_UNSPECIFIED\x10\x00\x12 \n\x1cMEMOS_SEARCH_TYPE_SUB_STRING\x10\x01\x12(\n$MEMOS_SEARCH_TYPE_REGULAR_EXPRESSION\x10\x02\x32r\n\x0cMemosService\x12\x62\n\x05Memos\x12+.systemathics.apis.services.v1.MemosRequest\x1a,.systemathics.apis.services.v1.MemosResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,systemathics_dot_apis_dot_type_dot_v1_dot_memo__pb2.DESCRIPTOR,])

_MEMOSSEARCHTYPE = _descriptor.EnumDescriptor(
  name='MemosSearchType',
  full_name='systemathics.apis.services.v1.MemosSearchType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MEMOS_SEARCH_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEMOS_SEARCH_TYPE_SUB_STRING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEMOS_SEARCH_TYPE_REGULAR_EXPRESSION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=427,
  serialized_end=555,
)
_sym_db.RegisterEnumDescriptor(_MEMOSSEARCHTYPE)

MemosSearchType = enum_type_wrapper.EnumTypeWrapper(_MEMOSSEARCHTYPE)
MEMOS_SEARCH_TYPE_UNSPECIFIED = 0
MEMOS_SEARCH_TYPE_SUB_STRING = 1
MEMOS_SEARCH_TYPE_REGULAR_EXPRESSION = 2



_MEMOSREQUEST = _descriptor.Descriptor(
  name='MemosRequest',
  full_name='systemathics.apis.services.v1.MemosRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_string', full_name='systemathics.apis.services.v1.MemosRequest.search_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search_type', full_name='systemathics.apis.services.v1.MemosRequest.search_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='systemathics.apis.services.v1.MemosRequest.start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='systemathics.apis.services.v1.MemosRequest.count', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=341,
)


_MEMOSRESPONSE = _descriptor.Descriptor(
  name='MemosResponse',
  full_name='systemathics.apis.services.v1.MemosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='memos', full_name='systemathics.apis.services.v1.MemosResponse.memos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='has_more', full_name='systemathics.apis.services.v1.MemosResponse.has_more', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=424,
)

_MEMOSREQUEST.fields_by_name['search_type'].enum_type = _MEMOSSEARCHTYPE
_MEMOSREQUEST.fields_by_name['start'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_MEMOSREQUEST.fields_by_name['count'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_MEMOSRESPONSE.fields_by_name['memos'].message_type = systemathics_dot_apis_dot_type_dot_v1_dot_memo__pb2._MEMO
DESCRIPTOR.message_types_by_name['MemosRequest'] = _MEMOSREQUEST
DESCRIPTOR.message_types_by_name['MemosResponse'] = _MEMOSRESPONSE
DESCRIPTOR.enum_types_by_name['MemosSearchType'] = _MEMOSSEARCHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemosRequest = _reflection.GeneratedProtocolMessageType('MemosRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEMOSREQUEST,
  '__module__' : 'systemathics.apis.services.v1.memos_pb2'
  # @@protoc_insertion_point(class_scope:systemathics.apis.services.v1.MemosRequest)
  })
_sym_db.RegisterMessage(MemosRequest)

MemosResponse = _reflection.GeneratedProtocolMessageType('MemosResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEMOSRESPONSE,
  '__module__' : 'systemathics.apis.services.v1.memos_pb2'
  # @@protoc_insertion_point(class_scope:systemathics.apis.services.v1.MemosResponse)
  })
_sym_db.RegisterMessage(MemosResponse)



_MEMOSSERVICE = _descriptor.ServiceDescriptor(
  name='MemosService',
  full_name='systemathics.apis.services.v1.MemosService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=557,
  serialized_end=671,
  methods=[
  _descriptor.MethodDescriptor(
    name='Memos',
    full_name='systemathics.apis.services.v1.MemosService.Memos',
    index=0,
    containing_service=None,
    input_type=_MEMOSREQUEST,
    output_type=_MEMOSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEMOSSERVICE)

DESCRIPTOR.services_by_name['MemosService'] = _MEMOSSERVICE

# @@protoc_insertion_point(module_scope)
