name: Upload Python Package

on: 
  push:
    tags: v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine grpcio grpcio-tools protobuf
    - name: Set VERSION environment variable
      run: |
        echo GitHub_ref: $GITHUB_REF
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        echo Version: $VERSION
        VERSION="${VERSION//v}"
        echo Clean Version: $VERSION
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Build and publish
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_ORG_TOKEN }}
      run: |
        python ./build.py